GET http://localhost:8080/api/produtos

###

POST http://localhost:8080/api/produtos
Content-Type: application/json

{
    "descricao":"camisa amarela.",
    "quantidade": 10,
    "valorCusto": 100.0,
    "valorVenda": 150.00
}