GET http://localhost:8080/api/enderecos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NTkyMDUwLCJleHAiOjE2OTc2Nzg0NTB9.iyL20hHbg2LOL6pm5HAT76H21paSaRDPU2SzdYxOEos
Content-Type: application/json
###

GET http://localhost:8080/api/enderecos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NjczNTU1LCJleHAiOjE2OTc3NTk5NTV9.BF3af3-ZY6rvXeTGjGgYUDZr4MYG9aqlf_jlqvcigMU
###

POST http://localhost:8080/api/enderecos
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3Njc2NzUwLCJleHAiOjE2OTc3NjMxNTB9.8R_w_0JQ_e_FETAeYudjSVgMJNQlfstP4dcuRvmO3m0

{
    "cep":"2898542",
    "logradouro": "Rua das Amélias",
    "numero": 50,
    "complemento": "CASA 03",
    "bairro": "Bairro XYZ",
    "cidade":"Teresópolis",
    "uf": "RJ",
    "titular": {
        "id": 2
    }
}
### 

PUT http://localhost:8080/api/enderecos/4
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3Njc3Mjk0LCJleHAiOjE2OTc3NjM2OTR9.jItZBfcLLp5OuLYeEw8cd9zMJ1ceRYHVrHdu32MOSMA

{
    "cep":"2898542",
    "logradouro": "Rua das Amoras",
    "numero": 80,
    "complemento": "CASA 03",
    "bairro": "Bairro XYZ",
    "cidade":"Teresópolis",
    "uf": "RJ",
    "titular": {
        "id": 2
    }
}
###

DELETE  http://localhost:8080/api/enderecos/1

###

GET http://localhost:8080/api/enderecos/email
Content-Type: application/json